name: Generate release
description: Default template for generating releases
title: "Release x.x.x"
body:
  - type: markdown
    attributes:
      value: Update title with the new version you want to release and create the issue, further instructions will appear as comments.
  - type: checkboxes
    id: autonomous
    attributes:
      label: Autonomous release?
      description: CI/CD pipeline will auto-merge all pull requests after checks passes
      options:
        - label: Yes, autonomous
